apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: "trainereks"    # change
  region: "us-east-1"   # change
  version: "1.30"
  tags:
    karpenter.sh/discovery: "trainereks"   # change
iam:
  withOIDC: true
  podIdentityAssociations:
  - namespace: "kube-system"
    serviceAccountName: karpenter
    roleName: trainereks-karpenter
    permissionPolicyARNs:
      - arn:aws:iam::975050323630:policy/KarpenterControllerPolicy-trainereks      

iamIdentityMappings:
- arn: "arn:aws:iam::975050323630:role/KarpenterNodeRole-trainereks"            
  username: system:node:{{EC2PrivateDNSName}}
  groups:
    - system:bootstrappers
    - system:nodes
vpc:
  cidr: 192.168.0.0/16
addons:
  - name: eks-pod-identity-agent
    version: latest
managedNodeGroups:
  - name: default
    desiredCapacity: 1
    minSize: 1
    maxSize: 3
    instanceType: t3.medium
    amiFamily: AmazonLinux2
