apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: ${CLUSTER_NAME}
  region: ${AWS_DEFAULT_REGION}
  version: 1.30
  tags:
    karpenter.sh/discovery: ${CLUSTER_NAME}

iam:
  withOIDC: true
managedNodeGroups:
- instanceType: m5.large
  amiFamily: t3.medium
  name: managedng
  desiredCapacity: 2
  minSize: 2
  maxSize: 5
addons:
- name: eks-pod-identity-agent
