name: SQL Deployment Check

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check-sql:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set execute permissions
      run: chmod +x scripts/check_sql.sh

    - name: Run SQL validation script
      run: ./scripts/check_sql.sh
